dist: xenial
language: python
python:
  - "3.7"

addons:
  sonarcloud: "a2564872c2fcb089fa87873235f54727b001c37e"
    organization: "7fe7e038f4db792b5cbe01748532d3830669ec20"
    token:
      secure: "01b6f590188f07bb201d2925c56eda8601a6005a"

before_install:
  - pip install -U pip

install:
  - pip install -r requirements-dev.txt codecov

script:
  - pylint dork tests
  - flake8 dork tests
  - coverage erase
  - coverage run --branch --source=dork --omit=dork/__main__.py -m pytest
  - coverage report -m
  
after_success:
  - coverage xml -i
  - codecov
  - sonar-scanner -Dsonar.projectKey=${SONAR_PROJECT_KEY} -Dsonar.organization=${SONAR_ORGANIZATION}
